pythoncapi_compat.h
Visual C++ 2008 fails with a compiler error on "inline" keyword when
building a C file.
=> Fix compatibility with Visual Studio 2013

COPYING, pythoncapi_compat.h
The COPYING file was copied from https://github.com/psf/pyperf/
without updating the copyright.
Follow recommendations of the Linux Foundation:
https://www.linuxfoundation.org/en/blog/copyright-notices-in-open-source-software-projects/
=> Update the copyright

pythoncapi_compat.h
Unfortunately, building fails with MSVC in pre-C99 mode (compiling against Python 2.7):
```
c:\temp\bitarray\bitarray\pythoncapi_compat.h(264) : error C2143: syntax error : missing ';' before 'type'
c:\temp\bitarray\bitarray\pythoncapi_compat.h(265) : error C2065: 'res' : undeclared identifier
c:\temp\bitarray\bitarray\pythoncapi_compat.h(268) : error C2065: 'res' : undeclared identifier
```
Hopefully an uncontroversial fix!
Thanks, Andrew R
=> Fix pre-C99 compilation

docs/api.rst, docs/changelog.rst, pythoncapi_compat.h, runtests.py, tests/setup.py, tests/test_pythoncapi_compat.py, tests/test_pythoncapi_compat_cext.c, tests/test_pythoncapi_compat_cppext.cpp
* pythoncapi_compat.h uses nullptr and reinterpret_cast<> on C++
* Add tests/test_pythoncapi_compat_cppext.cpp
=> Add C++ support

pythoncapi_compat.h
This reverts commit ca6a60ec284484ff4ae0cd12f7e3251afb2f74de.
=> Revert "Issue #21: Avoid C++ keyword `module` (#22)"

README.rst
How about something like this? I deliberately removed details to make it concise.
Resolves #23
=> Add a quick-start guide to the repo README

pythoncapi_compat.h, tests/test_pythoncapi_compat_cext.c
Remove _Py_StealRef() and _Py_XStealRef() functions.
=> Use Python 3.11 _Py_CAST() macro

pythoncapi_compat.h
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)
PyPy 7.3.11 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)
Tests run fine on pypy 7.3.11 with those 2 changes
Ran 24 tests in 0.154s
OK
Python 2.7 (release build): 11 C tests succeeded!
Ignore missing Python executable: python3.4
Ignore missing Python executable: python3.5
Ignore missing Python executable: python3.6
Ignore missing Python executable: python3.7
Ignore missing Python executable: python3.8
CPython 3.9 (release build): 11 C tests succeeded!
CPython 3.9 (release build): 11 C++03 tests succeeded!
CPython 3.9 (release build): 11 C++11 tests succeeded!
Ignore missing Python executable: python3.10
Ignore missing Python executable: python3.11
Ignore missing Python executable: python3.12
Ignore missing …
=> fix for pypy3.9-v7.3.11

docs/api.rst, docs/changelog.rst, pythoncapi_compat.h
Mercurial 6.2 released in July 2022 removed support for Python 2.7. It was the last project using pythoncapi_compat.h which required Python 2.7 support (on Windows).
Remove PYCAPI_COMPAT_STATIC_INLINE() macro: use "static inline" directly.
See:
* https://www.mercurial-scm.org/downloads
* https://wiki.mercurial-scm.org/SupportedPythonVersions
=> Remove support for Python 2.7 on Windows

tests/setup.py
Fix setup.py when the C compiler command has the "-std=c11" option. Remove "-std=" options from the compiler command.
=> Fix setup.py when CC contains -std=c11 option

docs/api.rst, pythoncapi_compat.h, tests/test_pythoncapi_compat_cext.c
Add PyMapping_HasKeyWithError() and PyMapping_HasKeyStringWithError() functions.
Fix also undefined behavior in PyMapping_GetOptionalItemString() when PyUnicode_FromString() fails: set '*result' to NULL.
=> Add PyMapping_HasKeyWithError() function

docs/api.rst, docs/changelog.rst, pythoncapi_compat.h, tests/test_pythoncapi_compat_cext.c
Add PyObject_HasAttrWithError() and PyObject_HasAttrStringWithError() functions.
Fix PyObject_GetOptionalAttrString(): set result to NULL on error.
=> Add PyObject_HasAttrWithError()

pythoncapi_compat.h
Follow on from https://github.com/python/pythoncapi-compat/pull/99.
`PyLong_GetSign` will be added in 3.14.0a0:
* https://github.com/python/cpython/pull/116561
I was getting an error building with latest `main`:
```pytb
In file included from src/encode.c:28:
src/thirdparty/pythoncapi_compat.h:1285:1: error: static declaration of 'PyLong_GetSign' follows non-static declaration
PyLong_GetSign(PyObject *obj, int *sign) {
^
/Users/hugo/github/python/cpython/main/Include/cpython/longobject.h:66:17: note: previous declaration is here
PyAPI_FUNC(int) PyLong_GetSign(PyObject *v, int *sign);
^
1 error generated.
```
Fix the version check and comment.
=> PyLong_GetSign will be added in 3.14a0

docs/changelog.rst, pythoncapi_compat.h, tests/test_pythoncapi_compat_cext.c
=> Add PyUnicodeWriter API

pythoncapi_compat.h
Add static inline to PyUnicodeWriter_WriteStr()
PyUnicodeWriter_WriteRepr().
=> Add static inline to PyUnicodeWriter_WriteStr

pythoncapi_compat.h
After updating mypyc to the latest `pythoncapi_compat.h`, the `cp313-win` wheel builds started to fail.
```
C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.13.0\tools\include\internal\pycore_unicodeobject.h(262): error C2375: '_PyUnicode_Equal': redefinition; different linkage
D:\a\mypy_mypyc-wheels\mypy_mypyc-wheels\mypy\mypyc\lib-rt\pythoncapi_compat.h(1540): note: see declaration of '_PyUnicode_Equal'
C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.13.0\tools\include\internal\pycore_pyhash.h(24): error C2375: '_Py_HashBytes': redefinition; different linkage
D:\a\mypy_mypyc-wheels\mypy_mypyc-wheels\mypy\mypyc\lib-rt\pythoncapi_compat.h(1567): note: see declaration of '_Py_HashBytes'
``` …
=> Fix 'redefinition; different linkage' errors with cp313-win

pythoncapi_compat.h, tests/test_pythoncapi_compat_cext.c
Those added in
https://github.com/pypy/pypy/commit/5661dff36f1120e458374954ca2353b87b951089 which is available in PyPy 7.3.8+.
=> Relax PYPY_VERSION_NUM requirements for hash macros

pythoncapi_compat.h, runtests.py, tests/test_pythoncapi_compat.py, tests/test_pythoncapi_compat_cext.c
We are working on PyPy3.11. It requires some adjustments here:
- Finally implemented `PyThreadState_GetInterpreter` and `PyGC_Collect`.
- I will argue that the managed dict strategy is an implementation detail. I excluded PyPy3.11 from the test of it, and will make creating a PyTypeObject with that flag enabled an error.
- Currently `_PyObject_GetDictPtr` returns `NULL` on PyPy. That is probably a bug. In any case, the test should not segfault by dereferencing a NULL pointer so I added a check.
=> prepare for pypy3.11 release

docs/users.rst
PyGObject, the Python bindings for GTK, recently starting using pythoncapi-compat to help modernize our code: https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/360. Thanks for the great library.
=> Add PyGObject as a user

docs/api.rst, docs/changelog.rst, pythoncapi_compat.h, tests/test_pythoncapi_compat_cext.c
PyPy is not supported, as well as Py2.  In the later case it's possible, but hardly worth code complications: most real-word potential consumers (e.g. Sage, gmpy2 or python-flint) support only Python 3.
=> Add PyLong Import/Export API

pythoncapi_compat.h
While testing the lastest changes in `pythoncapi_compat.h` with mypy, I encountered this error
```
pythoncapi_compat.h:1972: multiple definition of `Py_fclose'
```
Believe `Py_fclose` is missing `static inline`.
=> Fix multiple definitions for `Py_fclose`

pythoncapi_compat.h
Replace Py_ARRAY_LENGTH(array) with sizeof(array)/sizeof(array[0]).
Py_ARRAY_LENGTH() fails with C++ on Python 3.9 on macOS.
=> Avoid Py_ARRAY_LENGTH()

pythoncapi_compat.h
Original mypy fix by Michael R. Crusoe.
=> Don't redefine _Py_NULL macro if already defined

tests/test_upgrade_pythoncapi.py, upgrade_pythoncapi.py
In case we use \n on Windows or \r\n on Linux we don't want patching files to change every line due to newlines being adjusted to the platform defaults.
Instead pass 'newline=""' to all open() calls to preserve newlines. And when adding new lines use the first type of newline found in the file.
The test changes make the patching code reuseable and adds a second test with multiple different newlines in the input.
=> upgrade_pythoncapi: try to preserve newlines when patching

pythoncapi_compat.h
The %T format was added to Python 3.13 (PEP 737).
=> Avoid %T format in error message

pythoncapi_compat.h
I made a mistake in the format attribute. The third parameter should point to the location of the varargs arguments.
See https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-format-function-attribute.
=> Fix varargs indicator for PyBytesWriter_Format
